language: scala
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
language: python
python: "2.6"
install:
  - pip install inspyred
  - pip install argparse

# only build PRs and master (not all branch pushes)
branches:
  only:
    - master

